#+title: Emacs configuration
#+AUTHOR: Artem Khramov
#+OPTIONS: toc:3

* Bootstraping and tools
** Packages
*** Very first thing to do: native-comp
#+BEGIN_SRC emacs-lisp
(when (and (fboundp 'native-comp-available-p)
       (native-comp-available-p))
  (setq comp-deferred-compilation t))
#+END_SRC
*** Package sources
#+BEGIN_SRC emacs-lisp
(require 'package)
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
#+END_SRC

Use MELPA as primary source
#+BEGIN_SRC emacs-lisp
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
#+END_SRC

Add org-contrib repo.
#+BEGIN_SRC emacs-lisp
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/"))
#+END_SRC

We're all set up.
#+BEGIN_SRC emacs-lisp
(package-initialize)
#+END_SRC

*** use-package
Don't forget to install ~use-package~. ~use-package~ is the core of
this config.
#+BEGIN_SRC emacs-lisp
(unless (package-installed-p 'use-package) (package-install 'use-package))
#+END_SRC

* Tuning defaults
** Turning off menubar
As a heavy keyboard user, I never used the menubar anyway.
#+BEGIN_SRC emacs-lisp
(menu-bar-mode -1)
(tool-bar-mode -1)
#+END_SRC
** Enabling downcase and upcase region commands
I'm not sure why beginners find ~downcase-region~ and
~upcase-region~ commands confusing. Let's enable them.
#+BEGIN_SRC emacs-lisp
(put 'downcase-region 'disabled nil)
(put 'upcase-region 'disabled nil)
#+END_SRC
** Deleting trailing whitespaces before save
#+BEGIN_SRC emacs-lisp
(add-hook 'before-save-hook 'delete-trailing-whitespace)
#+END_SRC
** Setting up environment
#+BEGIN_SRC emacs-lisp
(use-package exec-path-from-shell
  :ensure t
  :init (exec-path-from-shell-initialize))
#+END_SRC

** Customize
Customizations will be stored in ~customizations.el~
#+BEGIN_SRC emacs-lisp
(use-package customizations
  :defer t
  :init
  (setq custom-file (locate-user-emacs-file "customizations.el"))
  (load custom-file))
#+END_SRC

* Features
** Crypto
Enter pins inside emacs

#+BEGIN_SRC emacs-lisp
(use-package pinentry
  :init
  (setenv "INSIDE_EMACS" "true")
  (pinentry-start))
#+END_SRC

** Command completion
*** Ivy
This config uses [[https://github.com/abo-abo/swiper][Ivy]] as completion frontend.
#+BEGIN_SRC emacs-lisp
(use-package ivy :ensure t)
#+END_SRC

~multi-term~ is for managing terminal buffers. ~Ivy~ is for managing
~multi-term~.
#+BEGIN_SRC emacs-lisp
(use-package ivy-mt
  :load-path
  (lambda () (locate-user-emacs-file "lisp"))
  :bind
  ("C-x p" . ivy-mt)
  :config
  (defun ivy-mt-buffer-list ()
    "Retrieve buffers list."
    (if (projectile-project-p)
	(projectile-project-buffers)
      (buffer-list)))

  (defun ivy-mt-launch-term ()
    "Launch new terminal."
    (if (projectile-project-p)
	(cd (projectile-project-root)))

    (call-interactively 'multi-vterm)))
#+END_SRC

Other completion functions
#+BEGIN_SRC emacs-lisp
(use-package counsel :ensure t)

(use-package counsel-projectile
  :ensure t
  :init (counsel-projectile-mode))
#+END_SRC

*** M-x enhancement
#+BEGIN_SRC emacs-lisp
(use-package smex
  :ensure t
  :bind
  ("M-x" . smex))
#+END_SRC


** Project interaction
#+BEGIN_SRC emacs-lisp
(use-package projectile
   :init
   (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
   (projectile-mode)
   :custom
   (projectile-switch-project-action
      (lambda ()
        (progn
         (require 'subr-x)
         (if-let* ((last-buffer (nth 1 (projectile-project-buffers))))
                   (switch-to-buffer last-buffer)
           (projectile-dired))))))
#+END_SRC

Switch to project buffers using ~projectile-switch-to-buffer~,
fallback to ~switch-to-buffer~ otherwise.
#+BEGIN_SRC emacs-lisp
(use-package akhramov-projectile-switch-to-buffer
  :load-path
  (lambda () (locate-user-emacs-file "package/lisp"))
  :bind
  ("C-x b" . akhramov-projectile-switch-to-buffer))
#+END_SRC


** Editing plugins
Drop-in replacement for standard ~comment-dwim~
#+BEGIN_SRC emacs-lisp
(use-package comment-dwim-2
  :ensure t
  :bind
  ("M-;" . comment-dwim-2))
#+END_SRC

Multicursor support
#+BEGIN_SRC emacs-lisp
(use-package multiple-cursors
  :ensure t
  :bind
  ("M-]" . mc/mark-next-like-this))
#+END_SRC

** Linting
#+BEGIN_SRC emacs-lisp
(use-package flycheck
  :ensure t
  :init
  (add-hook 'after-init-hook 'global-flycheck-mode))
#+END_SRC

** VCS
*** Git
#+BEGIN_SRC emacs-lisp
(use-package magit
  :ensure t
  :init
  (setf transient-default-level 5))
#+END_SRC
** Terminal support
#+BEGIN_SRC emacs-lisp
(use-package multi-vterm
  :ensure t
  :init)
#+END_SRC
** Org and authoring

#+BEGIN_SRC emacs-lisp
(use-package org-mode
  :bind ("C-c a" . org-agenda))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package org-wild-notifier
  :ensure t
  :init (org-wild-notifier-mode))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package gnuplot
  :ensure t)
#+END_SRC

** Misc
*** Alerts

#+BEGIN_SRC emacs-lisp
(use-package alert :ensure t)
#+END_SRC

Wild notifier. Spiky, but works. Upon click ~wild-notifier~
1. Focuses terminal
2. Executes commands (e.g. ~switch-buffer~)
#+BEGIN_SRC emacs-lisp
(when (string-equal system-type "darwin")
  (use-package wild-notifier
    :init (setf alert-default-style 'wild)
    :load-path (lambda () (locate-user-emacs-file "lisp"))))
#+END_SRC

* Languages
** Agda
#+BEGIN_SRC emacs-lisp
(use-package agda2-mode
  :mode "\\.agda\\'"
  :load-path
  (lambda () (file-name-directory (shell-command-to-string "agda-mode locate")))
  :init
  (bind-key "C-c ." 'agda2-goal-and-context-and-inferred)
  (bind-key "C-c C-s" 'agda2-solve-maybe-all))
#+END_SRC


** Elm
#+BEGIN_SRC emacs-lisp
(use-package elm-mode :ensure t)
#+END_SRC

** Javascript
#+BEGIN_SRC emacs-lisp
(use-package js2-mode
  :ensure t
  :init
  (add-hook 'js-mode-hook 'js2-minor-mode))
#+END_SRC

** Ruby
#+BEGIN_SRC emacs-lisp
(use-package enh-ruby-mode
  :ensure t
  :hook enh-ruby-mode)
#+END_SRC


** Vue
#+BEGIN_SRC emacs-lisp
(use-package vue-mode :ensure t)
#+END_SRC

** LSP languages
#+BEGIN_SRC emacs-lisp
(use-package lsp-mode :ensure t)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package typescript-mode
   :ensure t
  :hook ((typescript-mode . lsp)))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package typescript-mode
   :ensure t
  :hook ((typescript-mode . lsp)))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package lsp-java
   :ensure t
  :hook ((java-mode . lsp)))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package rust-ts-mode
  :hook ((rust-ts-mode . lsp)))
#+END_SRC
